dist: trusty
sudo: false
language: elixir
elixir: '1.9.1'
otp_release: '22.0.7'
matrix:
  include:
    - elixir: '1.7.3'
      otp_release: '20.3'
    - elixir: '1.8.1'
      otp_release: '21.3'
    - elixir: '1.9.1'
      otp_release: '22.0.7'

addons:
  postgresql: "9.4"
services:
  - postgresql
